version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 0
      context: ./
      dockerfile: PHP.Dockerfile
    image: hero
    container_name: hero-app
    restart: unless-stopped
    working_dir: /app/public/
    volumes:
      - ./:/app
    networks:
      - hero

  nginx:
    image: nginx:latest
    container_name: hero-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hero

networks:
  hero:
    driver: bridge
